name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Create environment file
      run: |
        echo "export const environment = {" > src/environments/environment.ts
        echo "  supabaseUrl: '${{ secrets.SUPABASE_URL }}'," >> src/environments/environment.ts
        echo "  supabaseKey: '${{ secrets.SUPABASE_KEY }}'" >> src/environments/environment.ts
        echo "};" >> src/environments/environment.ts

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test